language: julia
os:
    - linux
    - osx
julia:
    - 1.0
    - 0.7
    - nightly
matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false

codecov: true

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - julia --project=doc/ -e 'using Pkg; Pkg.instantiate();
                                    Pkg.develop(PackageSpec(path=pwd()))'
        - julia --project=doc/ doc/make.jl
      after_success: skip
